version: "3.5"
services:
    api:
        build:
            dockerfile: Dockerfile
            context: .
        depends_on: 
            - mariadb
        environment: 
            MARIADB_ROOT_PASSWORD: teste
            MARIADB_DATABASE: estacionamento
            MARIADB_USER: root
            NODE_ENV: development
            PORT: 3000
        ports:
            - "3000:3000"

    mariadb:
        image: mariadb
        restart: always
        ports:
        - 3306:3306
        env_file:
        - .env
        volumes:
        - ~/database/nest:/var/lib/mysql